name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      examplesRepo:
        description: 'The examples repo to use'
        required: true
        default: 'apache/activemq-artemis-examples'
        type: string
      examplesRepoBranch:
        description: 'Branch in examples repo'
        required: true
        default: 'development'
        type: string

env:
  EXAMPLES_REPO: ${{ inputs.examplesRepo || 'apache/activemq-artemis-examples' }}
  EXAMPLES_BRANCH: ${{ inputs.examplesRepoBranch || 'development' }}

jobs:
  test:
    name: Test (${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21, 25 ]

    steps:
      - uses: actions/checkout@v4
        with:
          path: activemq-artemis
          fetch-depth: 1
          show-progress: false

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      # By setting anything to org.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED we are disabling libaio loading on the testsuite
      - name: Fast Tests
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis
          mvn -B -s .github/maven-settings.xml -Dorg.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED=AnythingNotNull -Pfast-tests -Pcompatibility-tests verify

      - name: Archive Test Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-jdk-${{ matrix.java }}
          path: activemq-artemis/**/target/surefire-reports/*
          retention-days: 10

  checks:
    name: Checks (${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21, 25 ]

    steps:
      - uses: actions/checkout@v4
        with:
          path: activemq-artemis
          fetch-depth: 1
          show-progress: false

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Checkout Artemis Examples Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.EXAMPLES_REPO }}
          ref: ${{ env.EXAMPLES_BRANCH }}
          path: activemq-artemis-examples
          fetch-depth: 1
          show-progress: false

      - name: Build Main (JDK25 / -Prelease)
        if: matrix.java == '25'
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis
          mvn -B -T 1C -s .github/maven-settings.xml -DskipTests -Derrorprone -Pdev -Prelease -Dgpg.skip verify

      - name: Build Main (JDK <25)
        if: matrix.java != '25'
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis
          mvn -s .github/maven-settings.xml -DskipTests -Derrorprone -Pdev -Pjmh -Popenwire-tests -DskipActiveMQ5Tests verify

      - name: Set Examples Version to Artemis Version
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis
          CURRENT_ARTEMIS_BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current Artemis version: ${CURRENT_ARTEMIS_BUILD_VERSION}"
          cd ../activemq-artemis-examples
          ./scripts/update-examples-version.sh ${CURRENT_ARTEMIS_BUILD_VERSION}

      - name: Build Examples (JDK25 / -Prelease)
        if: matrix.java == '25'
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis-examples
          mvn -s ../activemq-artemis/.github/maven-settings.xml verify -Prelease

      - name: Build Examples (JDK <25 / -Pexamples,noRun)
        if: matrix.java != '25'
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis-examples
          mvn -s ../activemq-artemis/.github/maven-settings.xml verify -Pexamples,noRun

      - name: Javadoc Check (JDK25 / -Prelease)
        if: matrix.java == '25'
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis
          mvn -s .github/maven-settings.xml javadoc:javadoc -Prelease -DskipWebsiteDocGeneration=true -DskipWebsiteJavadocGeneration=true

      - name: Javadoc Check (JDK <25)
        if: matrix.java != '25'
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis
          mvn -s .github/maven-settings.xml javadoc:javadoc

      - name: Website Content Check (JDK25 only / -Prelease)
        if: matrix.java == '25'
        run: |
          export MAVEN_OPTS="-Xmx12G -Djava.io.tmpdir=/dev/shm"
          echo "MAVEN_OPTS=$MAVEN_OPTS"
          cd activemq-artemis
          mvn -s .github/maven-settings.xml clean verify -DskipTests -Prelease -am -pl "artemis-website"
